"""Generate complete reference YAML using only built-in synthetic metadata and placeholders."""
import json
from pathlib import Path

from general_runtime import build_error_topic, build_metadata_topic, build_query_topic
from studio_yaml import dumps

ROOT = Path(__file__).resolve().parent
BANNER = (
    "# SYNTHETIC REFERENCE: not a deployed agent snapshot.\n"
    "# Generated by example_topics.py; placeholders are intentionally not usable resource IDs.\n"
)
README = """# Complete synthetic native topics

These files show the complete current topic definitions, not abbreviated snippets.
They are **synthetic reference artifacts**, not an export of a deployed agent.
Only the invented `Entity` and `Event` schema and placeholder resource identifiers are used.
No live metadata, identities, business rows, connection state or credentials are included.

| File | Capability | Trigger |
|---|---|---|
| `ModelMetadata.mcs.yml` | Get model metadata | Generative selection |
| `GeneratedDaxQuery.mcs.yml` | Run generated DAX | Generative selection |
| `GeneratedDaxAdvice.mcs.yml` | Compile DAX advice | Generative selection |
| `GeneratedQueryError.mcs.yml` | Generated query error | OnError |

`index.json` lists the inputs, outputs, trigger, connector operations and related source.
The three callable capabilities are native topics, not the deleted fixed connector-tool cards.
The error handler is automatic rather than an independently selected query tool.

## Inspect the complete design

- `..\\agent.mcs.yml`: full agent instructions, capabilities, starters and model configuration.
- `..\\general_runtime.py`: topic generation and native Power Fx guards.
- `..\\generated_dax.py`: unrestricted expression boundary and bounded DAX envelope.
- `..\\query_transport.py`: dynamic result typing and envelope validation.
- `..\\metadata.example.json`: the same synthetic model used here.

Metadata accepts the fixed `primary` alias, a catalog/tables view and selected table names.
Query and advice accept generated table expressions, arbitrary declared output aliases, sorting,
row limit and optional paired date expressions. Their full input/output schemas are in the YAML.
Query execution uses fixed placeholder workspace/model/connection mappings and Invoker mode.
Advice does not execute the proposed business query. Error handling stops local decoder failures.

## Regenerate safely

From the example repository root, with its Python requirements installed:

```powershell
python example_topics.py
```

The script always uses built-in synthetic metadata and placeholder configuration. It does not
read `resources.json` or `model-schema.private.json`, and makes no network or deployment calls.
The files are deterministically generated from the same builders as the real implementation.

## Configure a real deployment separately

Do not import or publish these reference files unchanged. Follow the owner workflow in
`..\\README.md`: configure your own private resources, prepare and review your authorized model
metadata, generate private topics, validate, then deploy deliberately. A new model requires
its own schema preparation and permission-aware validation; these examples do not grant access.
"""


def synthetic_metadata():
    return {
        "example": True, "modelAlias": "primary",
        "source": "Synthetic shape example, not a live model export",
        "retrievedAtUtc": "2026-01-01T00:00:00+00:00",
        "tables": [
            {"name": "Entity", "description": "Synthetic entity dimension", "hidden": False,
             "columns": [{"name": "Key", "type": "string"}, {"name": "Owner", "type": "string"},
                         {"name": "Score", "type": "double"}], "measures": []},
            {"name": "Event", "description": "Synthetic event fact", "hidden": False,
             "columns": [{"name": "EntityKey", "type": "string"}, {"name": "Date", "type": "dateTime"}],
             "measures": [{"name": "Event Count", "description": "Synthetic count", "expressionAvailable": False}]},
        ],
        "relationships": [{"fromTable": "Event", "fromColumn": "EntityKey", "toTable": "Entity",
                           "toColumn": "Key", "isActive": True}],
        "guidance": {"authoredInstructions": "Not present in this synthetic example",
                     "verifiedAnswers": "Not present"},
    }


def placeholder_config():
    return {"workspaceId": "__WORKSPACE_ID__", "datasetId": "__DATASET_ID__",
            "connectionReference": "__CONNECTION_REFERENCE__"}


def render_examples():
    config, metadata = placeholder_config(), synthetic_metadata()
    topics = {
        "ModelMetadata": build_metadata_topic(config, metadata),
        "GeneratedDaxQuery": build_query_topic(config, metadata),
        "GeneratedDaxAdvice": build_query_topic(config, metadata, advice=True),
        "GeneratedQueryError": build_error_topic(),
    }
    index = {"syntheticReferenceOnly": True, "deployedSnapshot": False,
             "schemaPrefixPlaceholder": "__AGENT_SCHEMA_NAME__", "generator": "..\\example_topics.py",
             "metadata": "..\\metadata.example.json", "agentInstructions": "..\\agent.mcs.yml", "topics": []}

    def connectors(actions):
        for action in actions:
            if action["kind"] == "InvokeConnectorAction":
                yield {"operation": action["operationId"], "mode": action["connectionProperties"]["mode"],
                       "connectionReference": action["connectionReference"]}
            for branch in action.get("conditions", []):
                yield from connectors(branch.get("actions", []))

    files = {}
    for name, topic in topics.items():
        file = name + ".mcs.yml"
        files[file] = BANNER + dumps(topic)
        index["topics"].append({
            "file": file, "schemaSuffix": "topic." + name,
            "displayName": topic.get("modelDisplayName", "Generated query error"),
            "trigger": topic["beginDialog"]["kind"],
            "generativeSelection": topic["beginDialog"].get("intent", {}).get("includeInOnSelectIntent", False),
            "inputs": topic.get("inputType", {}).get("properties", {}),
            "outputs": topic.get("outputType", {}).get("properties", {}),
            "connectors": list(connectors(topic["beginDialog"]["actions"])),
        })
    files["index.json"] = json.dumps(index, indent=2) + "\n"
    files["README.md"] = README
    return files


def write_examples(root=ROOT):
    root = Path(root)
    output = root / "example-topics"
    output.mkdir(parents=True, exist_ok=True)
    files = render_examples()
    for name, content in files.items():
        (output / name).write_text(content, encoding="utf-8", newline="\n")
    return [str(Path("example-topics") / name) for name in files]


if __name__ == "__main__":
    print("Generated synthetic reference files:", ", ".join(write_examples()))
